import { Buffer } from 'node:buffer'

import { SparklePackagerConfigurationError } from './errors.ts'
import type { ElectronSparkleOptions } from './types.ts'

export const MINIMUM_SCHEDULED_CHECK_INTERVAL = 60 * 60

export function sparklePlistValues(
  options: ElectronSparkleOptions,
): Readonly<Record<string, string | boolean | number>> {
  validateElectronSparkleOptions(options)

  const values: Record<string, string | boolean | number> = {
    SUFeedURL: options.SUFeedURL,
    SUPublicEDKey: options.SUPublicEDKey,
  }

  const optionalValues = [
    ['SUEnableAutomaticChecks', options.SUEnableAutomaticChecks],
    ['SUAutomaticallyUpdate', options.SUAutomaticallyUpdate],
    ['SUAllowsAutomaticUpdates', options.SUAllowsAutomaticUpdates],
    ['SUScheduledCheckInterval', options.SUScheduledCheckInterval],
    ['SUShowReleaseNotes', options.SUShowReleaseNotes],
  ] as const

  for (const [key, value] of optionalValues) {
    if (value !== undefined) {
      values[key] = value
    }
  }

  return values
}

export function mergeSparklePlist(
  existing: Record<string, unknown> | null | undefined,
  values: Readonly<Record<string, string | boolean | number>>,
): Record<string, unknown> {
  const plist = existing ?? {}
  assertPlainRecord(plist, 'Info.plist configuration')

  for (const [key, value] of Object.entries(values)) {
    if (key in plist && plist[key] !== value) {
      throw new SparklePackagerConfigurationError(
        `Info.plist key ${key} conflicts with the electron-sparkle value. Remove it or set it to ${JSON.stringify(value)}.`,
      )
    }
  }

  return { ...plist, ...values }
}

export function assertPlainRecord(
  value: unknown,
  label: string,
): asserts value is Record<string, unknown> {
  if (
    typeof value !== 'object' ||
    value === null ||
    Array.isArray(value) ||
    Object.getPrototypeOf(value) !== Object.prototype
  ) {
    throw new SparklePackagerConfigurationError(
      `${label} must be an object. File-path and non-object plist configurations cannot be merged safely.`,
    )
  }
}

function validateElectronSparkleOptions(options: ElectronSparkleOptions): void {
  if (typeof options.SUFeedURL !== 'string' || options.SUFeedURL.trim().length === 0) {
    throw new SparklePackagerConfigurationError('SUFeedURL must be a non-empty HTTP or HTTPS URL.')
  }

  let parsedFeedURL: URL
  try {
    parsedFeedURL = new URL(options.SUFeedURL)
  } catch (error) {
    throw new SparklePackagerConfigurationError('SUFeedURL must be a valid HTTP or HTTPS URL.', {
      cause: error,
    })
  }

  if (!['http:', 'https:'].includes(parsedFeedURL.protocol) || !parsedFeedURL.hostname) {
    throw new SparklePackagerConfigurationError('SUFeedURL must be a valid HTTP or HTTPS URL.')
  }

  if (!isEncodedEd25519PublicKey(options.SUPublicEDKey)) {
    throw new SparklePackagerConfigurationError(
      'SUPublicEDKey must be a canonical base64-encoded 32-byte Ed25519 public key generated by Sparkle.',
    )
  }

  assertOptionalBoolean(options.SUEnableAutomaticChecks, 'SUEnableAutomaticChecks')
  assertOptionalBoolean(options.SUAutomaticallyUpdate, 'SUAutomaticallyUpdate')
  assertOptionalBoolean(options.SUAllowsAutomaticUpdates, 'SUAllowsAutomaticUpdates')
  assertOptionalBoolean(options.SUShowReleaseNotes, 'SUShowReleaseNotes')

  if (
    options.SUScheduledCheckInterval !== undefined &&
    (!Number.isFinite(options.SUScheduledCheckInterval) ||
      options.SUScheduledCheckInterval < MINIMUM_SCHEDULED_CHECK_INTERVAL)
  ) {
    throw new SparklePackagerConfigurationError(
      `SUScheduledCheckInterval must be a finite number of seconds no smaller than ${MINIMUM_SCHEDULED_CHECK_INTERVAL}.`,
    )
  }
}

export function hasMasTarget(value: unknown): boolean {
  if (typeof value === 'string') {
    return value === 'mas' || value === 'mas-dev'
  }

  if (Array.isArray(value)) {
    return value.some(hasMasTarget)
  }

  if (typeof value === 'object' && value !== null && 'target' in value) {
    return hasMasTarget(value.target)
  }

  return false
}

function isEncodedEd25519PublicKey(value: unknown): value is string {
  if (typeof value !== 'string' || !/^[A-Za-z0-9+/]{43}=$/.test(value)) {
    return false
  }

  const decoded = Buffer.from(value, 'base64')
  return decoded.byteLength === 32 && decoded.toString('base64') === value
}

function assertOptionalBoolean(value: unknown, name: string): void {
  if (value !== undefined && typeof value !== 'boolean') {
    throw new SparklePackagerConfigurationError(`${name} must be a boolean when provided.`)
  }
}
